title:  Kevin Waters
tagline:  A personal portfolio

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'Coding', path: 'menu', url: 'coding.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'CV', path: 'assets/docs', url: 'KWaters_CV.pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/kwaters4'}
- {icon: 'envelope', link: 'mailto:kwaters@mtu.edu'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
